---
title: "04.BP2_BK"
author: "yaozhong_zhang"
date: "2025-08-06"
output: html_document
---
# 读入模拟样品分组与真实值
```{r}
path <- getwd()
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = path)

# 加载分析包
package <- c('readxl','magrittr','LorMe','randomForest',
             'ggtree','reshape2','dplyr','tidyr',
             'readr','purrr','tibble','stringr','forcats',
             'ggplot2','ggsci','ggridges','RColorBrewer','pheatmap',
             'patchwork','ggpubr','zyzPackage','cowplot','ggrepel','networkD3','UpSetR','ggvenn','ggalluvial','sampling')
             
lapply(package, function(x){library(x, character.only = T)})
```

# 读入-分析数据库
```{r}
load(file = "01.rawdata/UniPathogenDB/UniPathogenDB.Rdata")
load(file = "02.datasave/04.BPBK_P.Rdata")
```


# 读入-真实值预测值
```{r}
attach(ARGsTvalue)
attach(ARGsBP)
attach(ARGsContigs)
attach(ARGsReads)


df1 <- BacTvalue %>% dplyr::select(ID,everything(),-Taxonomy,Lineage)

#' 生成各分类层级的丰度表
#' 生成各分类层级的丰度表，将NA归类为unKnown
#'
#' @param df 输入数据框，必须包含Lineage列和丰度列
#' @param abundance_pattern 丰度列的正则表达式模式，默认为"^T3-|^T4-"
#' @param taxonomy_levels 需要提取的分类层级，默认为所有7个层级
#' @param unknown_label NA值的替换标签，默认为"unKnown"
#' @return 包含各分类层级丰度表的列表
#'
generate_taxonomy_abundance <- function(df, abundance_pattern = "^T3-|^T4-", 
                                       taxonomy_levels = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"),
                                       unknown_label = "unKnown") {
  
  library(dplyr)
  library(tidyr)
  
  # 拆分Lineage列
  df_split <- df %>%
    separate(Lineage, into = taxonomy_levels, sep = ";", remove = FALSE, fill = "right")
  
  # 将NA值替换为unKnown
  df_split <- df_split %>%
    mutate(across(all_of(taxonomy_levels), ~ifelse(is.na(.) | . == "", unknown_label, .)))
  
  # 提取丰度列
  abundance_cols <- grep(abundance_pattern, colnames(df_split), value = TRUE)
  
  # 创建空列表存储结果
  result_list <- list()
  
  # 为每个分类层级生成丰度表
  for (level in taxonomy_levels) {
    level_abundance <- df_split %>%
      group_by(!!sym(level)) %>%
      summarise(across(all_of(abundance_cols), \(x) sum(x, na.rm = TRUE)), .groups = "drop")
    level_abundance <- as.data.frame(level_abundance)
    # 重命名第一列为分类层级名称
    colnames(level_abundance)[1] <- level
    
    result_list[[level]] <- level_abundance
  }
  
  return(result_list)
}

# 使用示例

# 使用示例
# taxonomy_abundance_list <- generate_taxonomy_abundance(df1)

# 如果你想指定特定的丰度列模式：
# taxonomy_abundance_list <- generate_taxonomy_abundance(df1, abundance_pattern = "^T3-|^T4-")

# 如果你只想提取部分分类层级：
# taxonomy_abundance_list <- generate_taxonomy_abundance(df1, taxonomy_levels = c("Phylum", "Class", "Order"))
BacList<- generate_taxonomy_abundance(BacTvalue, abundance_pattern = "^T3-|^T4-")
ARGsList<- generate_taxonomy_abundance(ARGsTvalue, abundance_pattern = "^T3-|^T4-")
ARGsBPList<- generate_taxonomy_abundance(ARGsBP, abundance_pattern = "^T3-|^T4-")
ARGsReadsList<- generate_taxonomy_abundance(ARGsReads, abundance_pattern = "^T3-|^T4-")
ARGsContigsList<- generate_taxonomy_abundance(ARGsContigs, abundance_pattern = "^T3-|^T4-")

# 相关性分析脚本
# df1 and df2: 相关性分析矩阵,默然是format2形式
# name1: 作为x轴的坐标名称
# name2: 作为y轴的坐标名称
df1 <- ARGsBPList$Species
matrix_combine <- function(df1,df2,name1,name2){
  df1 <- df1; df1 <- bptracer::profile_sweep(df1)
  df2 <- df2; df2 <- bptracer::profile_sweep(df2)
  
  colnames(df1)[1] <- "ID";colnames(df2)[1] <- "ID"
  df1_melt <- rownames_zyz(df1,transform = T) %>% rownames_zyz(.,transform = F,cbindrowname = T) %>% reshape2::melt(.,1)
  df2_melt <- rownames_zyz(df2,transform = T) %>% rownames_zyz(.,transform = F,cbindrowname = T) %>% reshape2::melt(.,1)
  df12_melt <- full_join(df1_melt,df2_melt, by = c("ID", "variable"))
  colnames(df12_melt) <- c("ID","variable",name1,name2)
  df12_melt[is.na(df12_melt)] <- 0
  return(df12_melt)
}
```


# 主图-真实值预测值相关性分析
```{r}
# 模拟宏基因组物种分类表，以及病原菌数据库，确定病原菌数据的
attach(refseq_sim_1200)
CorARGsBP1 <- matrix_combine(df1 =ARGsBPList$Species,df2 =ARGsList$Species,name1 = "Pvalue",name2 = "Tvalue")
CorARGsBP2 <- matrix_combine(df1 =ARGsBPList$Species,df2 =BacList$Species ,name1 = "Pvalue",name2 = "Tvalue")

CorARGsBP1$Kind <- ifelse(CorARGsBP1$variable %in% NewPA_Mini$ID, "Pathogen", "Nonpathogen")
CorARGsBP2$Kind <- ifelse(CorARGsBP2$variable %in% NewPA_Mini$ID, "Pathogen", "Nonpathogen")
CorARGsBP1 <- left_join(CorARGsBP1,NewPA_Mini,by=c("variable"="ID"))
CorARGsBP1$Type[is.na(CorARGsBP1$Type)] <- "NonPathogen"
CorARGsBP2 <- left_join(CorARGsBP2,NewPA_Mini,by=c("variable"="ID"))
CorARGsBP2$Type[is.na(CorARGsBP2$Type)] <- "NonPathogen"

# 测试数据，用来构建ggplot批量分析函数-----------------------
P_CorARGsBP1<- ggplot(CorARGsBP1,aes(x = Pvalue,y = Tvalue ,color=Type))+
  geom_jitter(alpha=.3)+
  geom_smooth(method = lm,show.legend = F)+
  stat_cor( method = "spearman",show.legend = F)+
  # facet_wrap(~Kind)+
  scale_x_log10()+
  scale_y_log10()+
  scale_colour_npg()+
  xlab("log10[True ARGs ppm abundance]")+
  ylab("log10[Predicted ARGs ppm abundance]")+
  # xlab(paste0(bquote(log[10]),"\\[Bacteria abundance\\]"))+
  # xlab("SARG Type ppm")+ylab("TAVMM ARG Type ppm")
  theme_jgf()
P_CorARGsBP1


P_CorARGsBP2<- ggplot(CorARGsBP2,aes(x = Pvalue,y = Tvalue,color=Type))+
  geom_jitter(alpha=.3)+
  geom_smooth(method = lm,show.legend = F)+
  stat_cor( method = "spearman",show.legend = F)+
  # facet_wrap(~Kind)+
  scale_x_log10()+
  scale_y_log10()+
  scale_colour_npg()+
  xlab("log10[True Bacteria relative abundance]")+
  ylab("log10[Predicted ARGs ppm abundance]")+
  # xlab(paste0(bquote(log[10]),"\\[Bacteria abundance\\]"))+
  # xlab("SARG Type ppm")+ylab("TAVMM ARG Type ppm")
  theme_jgf()
P_CorARGsBP2


# 构建可视化函数-----------------------
make_CorPlot <- function(df1, df2, NewPA_Mini,
                         xlab_text, ylab_text) {
  # 1. 数据处理
  CorData <- matrix_combine(df1 = df1, df2 = df2,
                            name1 = "Pvalue", name2 = "Tvalue")
  
  CorData$Kind <- ifelse(CorData$variable %in% NewPA_Mini$ID,
                         "Pathogen", "Nonpathogen")
  
  CorData <- left_join(CorData, NewPA_Mini, by = c("variable" = "ID"))
  CorData$Type[is.na(CorData$Type)] <- "NonPathogen"
  
  # 2. 画图
  p <- ggplot(CorData, aes(x = Pvalue, y = Tvalue, color = Type)) +
    geom_jitter(alpha = 0.3) +
    geom_smooth(method = lm, show.legend = FALSE) +
    stat_cor(method = "spearman", show.legend = FALSE) +
    scale_x_log10() +
    scale_y_log10() +
    scale_colour_npg() +
    xlab(xlab_text) +
    ylab(ylab_text) +
    theme_jgf()
  
  return(p)
}


make_CorPlot2 <- function(df1, df2, NewPA_Mini,
                         xlab_text, ylab_text) {
  # 1. 数据处理
  CorData <- matrix_combine(df1 = df1, df2 = df2,
                            name1 = "Pvalue", name2 = "Tvalue")
  
  CorData$Kind <- ifelse(CorData$variable %in% NewPA_Mini$ID,
                         "Pathogen", "Nonpathogen")
  
  CorData <- left_join(CorData, NewPA_Mini, by = c("variable" = "ID"))
  CorData$Type[is.na(CorData$Type)] <- "NonPathogen"
  
  # 2. 画图
  p <- ggplot(CorData, aes(x = Pvalue, y = Tvalue, color = Type)) +
    geom_jitter(alpha = 0.3) +
    geom_smooth(method = lm, show.legend = FALSE) +
    stat_cor(method = "spearman", show.legend = FALSE) +
    scale_x_log10() +
    scale_y_log10() +
    scale_colour_npg() +
    xlab(xlab_text) +
    ylab(ylab_text) +
    theme_jgf()
  
 # 返回包含数据和图形的列表
  return(list(CorData = CorData, Plot = p))
}



# ---------- BP ----------
# True ARGs vs Predicted ARGs
P_CorARGsBP1 <- make_CorPlot(
  df1 = ARGsBPList$Species,
  df2 = ARGsList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True ARGs abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)


# Bacteria vs Predicted ARGs
P_CorARGsBP2 <- make_CorPlot(
  df1 = ARGsBPList$Species,
  df2 = BacList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True Bacteria abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)


# ---------- Contigs ----------
# True ARGs vs Predicted ARGs
P_CorARGsContigs1 <- make_CorPlot(
  df1 = ARGsContigsList$Species,
  df2 = ARGsList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True ARGs abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)

# Bacteria vs Predicted ARGs
P_CorARGsContigs2 <- make_CorPlot(
  df1 = ARGsContigsList$Species,
  df2 = BacList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True Bacteria abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)


# ---------- Reads ----------
# True ARGs vs Predicted ARGs
P_CorARGsReads1 <- make_CorPlot(
  df1 = ARGsReadsList$Species,
  df2 = ARGsList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True ARGs abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)

# Bacteria vs Predicted ARGs
P_CorARGsReads2 <- make_CorPlot(
  df1 = ARGsReadsList$Species,
  df2 = BacList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True Bacteria abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)

# 拼接
# 或者六个图一起
P_CorARGsBP1 + P_CorARGsReads1 + P_CorARGsContigs1+
P_CorARGsBP2 + P_CorARGsReads2 + P_CorARGsContigs2 + plot_layout(guides = 'collect')
ggsave("03.figureUP/S_ARG_PA_cor.pdf",width = 9,height = 5)

####################


# ---------- BP ----------
# True ARGs vs Predicted ARGs
P_CorARGsBP1 <- make_CorPlot2(
  df1 = ARGsBPList$Species,
  df2 = ARGsList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True ARGs abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)

# Bacteria vs Predicted ARGs
P_CorARGsBP2 <- make_CorPlot2(
  df1 = ARGsBPList$Species,
  df2 = BacList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True Bacteria abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)


# ---------- Contigs ----------
# True ARGs vs Predicted ARGs
P_CorARGsContigs1 <- make_CorPlot2(
  df1 = ARGsContigsList$Species,
  df2 = ARGsList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True ARGs abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)

# Bacteria vs Predicted ARGs
P_CorARGsContigs2 <- make_CorPlot2(
  df1 = ARGsContigsList$Species,
  df2 = BacList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True Bacteria abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)


# ---------- Reads ----------
# True ARGs vs Predicted ARGs
P_CorARGsReads1 <- make_CorPlot2(
  df1 = ARGsReadsList$Species,
  df2 = ARGsList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True ARGs abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)

# Bacteria vs Predicted ARGs
P_CorARGsReads2 <- make_CorPlot2(
  df1 = ARGsReadsList$Species,
  df2 = BacList$Species,
  NewPA_Mini = NewPA_Mini,
  xlab_text = "log10[True Bacteria abundance]",
  ylab_text = "log10[Predicted ARGs abundance]"
)


P_CorARGsAll <- rbind(
  P_CorARGsBP1$CorData %>% mutate(Method = "BP-Tracer"),
  P_CorARGsContigs1$CorData %>% mutate(Method = "Contigs"),
  P_CorARGsReads1$CorData %>% mutate(Method = "Reads")
)
P_CorARGsAll2 <- rbind(
  P_CorARGsBP2$CorData %>% mutate(Method = "BP-Tracer"),
  P_CorARGsContigs2$CorData %>% mutate(Method = "Contigs"),
  P_CorARGsReads2$CorData %>% mutate(Method = "Reads")
)


P_CorARGs<- ggplot(P_CorARGsAll,aes(x = Pvalue,y = Tvalue ,color=Method))+
  geom_jitter(alpha=.1)+
  geom_smooth(method = lm,show.legend = F)+
  stat_cor( method = "spearman",show.legend = F)+
  # facet_wrap(~Kind)+
  scale_x_log10()+
  scale_y_log10()+
  scale_colour_futurama()+
  xlab("log10[True ARGs ppm abundance]")+
  ylab("log10[Predicted ARGs ppm abundance]")+
  # xlab(paste0(bquote(log[10]),"\\[Bacteria abundance\\]"))+
  # xlab("SARG Type ppm")+ylab("TAVMM ARG Type ppm")
  theme_jgf()
P_CorARGs



zyz_cols <-c("#8c2e2f","#33395d","#009399")
names(zyz_cols) <- c("BP-Tracer","Reads","Contigs")

P_CorARGs2<- ggplot(P_CorARGsAll2,aes(x = Tvalue,y = Pvalue ,color=Method))+
  geom_jitter(alpha=.1)+
  geom_smooth(method = lm,show.legend = F)+
  stat_cor( method = "spearman",show.legend = F)+
  # facet_wrap(~Kind)+
  scale_x_log10()+
  scale_y_log10()+
  scale_colour_manual(values = zyz_cols)+
  xlab("log10[True ARGs ppm abundance]")+
  ylab("log10[Predicted ARGs ppm abundance]")+
  # xlab(paste0(bquote(log[10]),"\\[Bacteria abundance\\]"))+
  # xlab("SARG Type ppm")+ylab("TAVMM ARG Type ppm")
  theme_jgf()
P_CorARGs2


P_CorARGs<- ggplot(P_CorARGsAll,aes(x = Tvalue,y = Pvalue ,color=Method))+
  geom_jitter(alpha=.1)+
  geom_smooth(method = lm,show.legend = F)+
  stat_cor( method = "spearman",show.legend = F)+
  # facet_wrap(~Kind)+
  scale_x_log10()+
  scale_y_log10()+
  scale_colour_futurama()+
  scale_colour_manual(values = zyz_cols)+
  xlab("log10(True bacteria abundance)")+
  ylab("log10(Predicted ARGs ppm abundance)")+
  # xlab(paste0(bquote(log[10]),"\\[Bacteria abundance\\]"))+
  # xlab("SARG Type ppm")+ylab("TAVMM ARG Type ppm")
  theme_jgf()
P_CorARGs2/P_CorARGs
ggsave(filename = "03.figureUP/M4_BK_Cor.pdf",height = 6,width = 4.4)

```


# 附图-BKBac物种丰度评估
```{r}
attach(BacBK)
ggplot()+
  # geom_point(data = df2, aes(x = level,y = value,color=Info,shape=SpeciesNumbers),alpha=.5)+
  geom_point(data =BacBK, aes(x = level,y = value,color=Info),alpha=.2)+
  # 第一条line虚线
  geom_line(data =BacBK,aes(x = level,y = value,group=group,color=Info),size=.8,alpha=.5,show.legend = F)+
   geom_errorbar(
    data = BKBac,
    aes(x = level,
        y = value,
        ymin = value - sd,
        ymax = value + sd,
        group = group,
        color = Info),
    width = 0.1,   # 误差线横向小帽宽度，可按需要调整
    size = 0.4,
    alpha = 0.6,
    show.legend = FALSE)+
  geom_hline(yintercept = 0.8,linetype='dotted', col = 'red')+
  facet_wrap(~variable,nrow = 3)+
  theme_jgfbw()+xlab("")+ylab("")+
  scale_y_continuous(labels = scales::percent) + 
  theme(axis.text.x = element_text(angle = 70, hjust = 0.5, vjust = 0.5))+
  labs("Info")+
  theme(legend.position = c(.68,.1))+
  guides(
    color = guide_legend(
      title = "Threshold (f₁)",   # 图例标题
      label.position = "top",     # 标签位置
      ncol = 3,                  # 设置为1列（如果想要多行分布）
      label.hjust = 0.5,         # 水平居中
      title.position = "top"     # 标题位置
    )
  )
ggsave("03.figureUP/S4_Bac_BK.pdf",height = 6,width = 6)


```





# 分析-BKCor
1. 获取功能基因丰度表以及物种丰度表
2. 基于Species水平和Subtypes水平进行分析
3. Species水平丰度过滤
4. Subtypes水平丰度过滤
5. 基于Network进行相关性
```{r}
# 原始数据读入——————————————————————————————————————
library(igraph)
library(LorMe04)
library(LorMe)
library(corpcor)
# 分组文件
Group_T3_order <- Group_TA %>% filter(Group=="T3") %>% .[,1]
Group_T4_order <- Group_TA %>% filter(Group=="T4") %>% .[,1]

# ARG_ppm_source_BP_100_25_G
ARG_ppm_subtype_SA <- read.delim("01.rawdata/BP2_BK/01.PredictedValue/06.Cor/SARG-OUT.ppm.subtype.txt",check.names = F);colnames(ARG_ppm_subtype_SA)[1] <- "ID"
ARG_ppm_type_SA <- read.delim("01.rawdata/BP2_BK/01.PredictedValue/06.Cor/SARG-OUT.ppm.type.txt",check.names = F);colnames(ARG_ppm_type_SA)[1] <- "ID"
Bac_kraken_S_ab <- read.delim("01.rawdata/BP2_BK/01.PredictedValue/06.Cor/taxonomy.table.S",check.names = F)
Bac_kraken_P_ab <- read.delim("01.rawdata/BP2_BK/01.PredictedValue/06.Cor/taxonomy.table.P",check.names = F)

# 输出Kraken2的TaxID，然后进行分析
cor_tax <- read.delim( "01.rawdata/BP2_BK/01.PredictedValue/06.Cor/taxonomy.S") %>% .[,c(1:2)] %>% unique()
uniq_c(cor_tax$taxonomy_id)
# write.table(cor_tax[,-1],file = "01.rawdata/BP2_BK/01.PredictedValue/06.Cor/taxonkit/species_taxid.txt",col.names = F,row.names = F)

# 读入taxonkit结果
cor_tax_refseq <- read.delim("01.rawdata/BP2_BK/01.PredictedValue/06.Cor/taxonkit/CorTax_refseq_240515_speciestaxid.taxonomyLineage.txt")
cor_tax_refseq <- bptracer::taxonomy_combine(inputtble = cor_tax_refseq,newcolname = "Taxonomy",colnames = c(2:8))
cor_tax_refseq <- bptracer::taxonomy_combine(inputtble = cor_tax_refseq,newcolname = "Lineage",colnames = c(9:15))
cor_tax_refseq <- cor_tax_refseq %>% select(species_taxid,Taxonomy,Lineage)
cor_tax_refseq <- left_join(cor_tax,cor_tax_refseq,by=c("taxonomy_id"="species_taxid"))
cor_tax_refseq <- cor_tax_refseq %>% select(-taxonomy_id)
colnames(cor_tax_refseq)[1] <- "ID"
# 测试是否可以完全匹配
df1 <- left_join(Bac_kraken_S_ab,cor_tax_refseq,by=c("ID"="ID"))


# 设置过滤条件-------------------------
# ARGs过滤：按照流行度进行过滤

filter=0
ARG_ppm_subtype_SA_Group3 <- ARG_ppm_subtype_SA %>% dplyr::select(ID,all_of(Group_T3_order)) %>% 
  cbind(.,temp="A") %>% LorMe04::Filter_function(.,threshold = filter ,format = 3,outformat = 1)%>% .[,-ncol(.)]
ARG_ppm_subtype_SA_Group4 <- ARG_ppm_subtype_SA %>% dplyr::select(ID,all_of(Group_T4_order)) %>% 
  cbind(.,temp="A") %>% LorMe04::Filter_function(.,threshold = filter ,format = 3,outformat = 1)%>% .[,-ncol(.)]
ARG_ppm_subtype_SA_fil <- full_join(ARG_ppm_subtype_SA_Group3,ARG_ppm_subtype_SA_Group4) 
ARG_ppm_subtype_SA_fil[is.na(ARG_ppm_subtype_SA_fil)] <- 0
sum(ARG_ppm_subtype_SA_fil$`T3-0`)/sum(ARG_ppm_subtype_SA$`T3-0`)

# Types相关分析
ARG_ppm_type_SA_Group3 <- ARG_ppm_type_SA %>% dplyr::select(ID,all_of(Group_T3_order)) %>% 
  cbind(.,temp="A") %>% LorMe04::Filter_function(.,threshold = filter ,format = 3,outformat = 1)%>% .[,-ncol(.)]
ARG_ppm_type_SA_Group4 <- ARG_ppm_type_SA %>% dplyr::select(ID,all_of(Group_T4_order)) %>% 
  cbind(.,temp="A") %>% LorMe04::Filter_function(.,threshold = filter ,format = 3,outformat = 1)%>% .[,-ncol(.)]
ARG_ppm_type_SA_fil <- full_join(ARG_ppm_type_SA_Group3,ARG_ppm_type_SA_Group4) 
ARG_ppm_type_SA_fil[is.na(ARG_ppm_type_SA_fil)] <- 0
sum(ARG_ppm_type_SA_fil$`T3-0`)/sum(ARG_ppm_type_SA$`T3-0`)





# 设置过滤条件-------------------------
# Bac过滤：除去物种丰度<5的数字
threshold <- 5
Bac_kraken_S_ab[Bac_kraken_S_ab < threshold] <- 0
# Bac过滤：按照流行度进行过滤
filter=0
Bac_kraken_S_ab_Group3 <- Bac_kraken_S_ab %>% dplyr::select(ID,all_of(Group_T3_order)) %>% 
  cbind(.,temp="A") %>% LorMe04::Filter_function(.,threshold = filter ,format = 3,outformat = 1)%>% .[,-ncol(.)]
Bac_kraken_S_ab_Group4 <- Bac_kraken_S_ab %>% dplyr::select(ID,all_of(Group_T4_order)) %>% 
  cbind(.,temp="A") %>% LorMe04::Filter_function(.,threshold = filter ,format = 3,outformat = 1)%>% .[,-ncol(.)]

Bac_kraken_S_ab_fil <- full_join(Bac_kraken_S_ab_Group3,Bac_kraken_S_ab_Group4)
Bac_kraken_S_ab_fil[is.na(Bac_kraken_S_ab_fil)] <- 0
sum(Bac_kraken_S_ab_fil$`T3-0`)/sum(Bac_kraken_S_ab$`T3-0`)


# 构建相关性网络分析-------------------------
attach(Bac_kraken_S_ab_fil)
attach(ARG_ppm_subtype_SA_fil)
attach(ARG_ppm_type_SA_fil)

# # 相关性分析-基于Types分析
# Cor1_types <- LorMe::network_analysis2(input = Bac_kraken_S_ab_fil,inputtype = 2,n = 15,threshold = 0.9,input2 = ARG_ppm_type_SA_fil,input2type = 2,method = "spearman",display = TRUE)
# Nodes_types <- Cor1_types$Nodes_info
# Nodes_types_Species <- Nodes_types[which(Nodes_types$nodes_id %in% Bac_kraken_S_ab_fil$ID ),]

# 相关性分析-基于Bac和Subtypes分析
Cor1_subtypes<- LorMe::network_analysis2(input = Bac_kraken_S_ab_fil,inputtype = 2,n = 15,threshold = 0.9,input2 = ARG_ppm_subtype_SA_fil,input2type = 2,method = "spearman",display = TRUE)
Nodes_subtypes <- Cor1_subtypes$Nodes_info
Nodes_subtypes_Species <- Nodes_subtypes[which(Nodes_subtypes$nodes_id %in% Bac_kraken_S_ab_fil$ID ),]

# 相关性分析-基于Bac和Subtypes分析
# n = 10，效果会更好一些
Cor2_subtypes<- LorMe::network_analysis2(input = Bac_kraken_S_ab_fil,inputtype = 2,n = 10,threshold = 0.9,input2 = ARG_ppm_subtype_SA_fil,input2type = 2,method = "spearman",display = TRUE)
Nodes_subtypes <- Cor1_subtypes$Nodes_info
Nodes_subtypes_Species <- Nodes_subtypes[which(Nodes_subtypes$nodes_id %in% Bac_kraken_S_ab_fil$ID ),]


Bac_kraken_S_ab_final <- left_join(Bac_kraken_S_ab_fil,cor_tax_refseq,by=c("ID")) %>% filter(ID %in%Nodes_subtypes_Species$nodes_id)
colnames(Bac_kraken_S_ab_final)[1] <- "TaxID"
write.table(Bac_kraken_S_ab_final,file = "01.rawdata/BP2_BK/01.PredictedValue/06.Cor/Cor.S.Abu.txt",quote = F,sep = "\t",row.names = F)
```


# 读入-BKBP
```{r}

library(stringr)
library(dplyr)

ARGsBPBK <- read.delim(file = "01.rawdata/BP2_BK/04.FinalBK/01.BP/BK.ARGs.Info.txt",check.names = F) 
MGEsBPBK <- read.delim(file = "01.rawdata/BP2_BK/04.FinalBK/01.BP/BK.MGEs.Info.txt",check.names = F) 
MRGsBPBK <- read.delim(file = "01.rawdata/BP2_BK/04.FinalBK/01.BP/BK.MRGs.Info.txt",check.names = F) 
SGsBPBK <- read.delim(file = "01.rawdata/BP2_BK/04.FinalBK/01.BP/BK.SGs.Info.txt",check.names = F) 
VFsBPBK <- read.delim(file = "01.rawdata/BP2_BK/04.FinalBK/01.BP/BK.VFs.Info.txt",check.names = F) 


GeneBPBK <- bind_rows(ARGsBPBK,MGEsBPBK,MRGsBPBK,SGsBPBK,VFsBPBK)
colnames(GeneBPBK)[2] <- "Level"
GeneBPBK <- left_join(GeneBPBK,Group_TA,by=c("Sample"="ID"))


GeneBPBK_Species <- GeneBPBK[which(GeneBPBK$Level=="Species"),]
GeneBPBK_Species_tgc1 <- Rmisc::summarySE(GeneBPBK_Species, measurevar="F1", groupvars=c("GeneKind")) 
GeneBPBK_Species_tgc2 <- Rmisc::summarySE(GeneBPBK_Species, measurevar="F1", groupvars=c("File","GeneKind")) 


# 按GeneKind和File分组，取每组平均F1最大的前15行
top15_per_kind_file <- GeneBPBK_Species_tgc2 %>%
  group_by(GeneKind, File) %>%
  slice_max(F1, n = 15) %>%     # 取每组F1最大的前15行
  ungroup()

# 显示结果
head(top15_per_kind_file)

# 每种GeneKind中取平均F1最大的File，然后取前15个
top15_avg_groups <- GeneBPBK_Species_tgc2 %>%
  group_by(GeneKind, File) %>%
  summarise(mean_F1 = mean(F1, na.rm = TRUE), .groups = 'drop') %>%
  group_by(GeneKind) %>%
  filter(mean_F1 == max(mean_F1)) %>%  # 每个GeneKind保留平均F1最大的File
  ungroup() %>%
  slice_max(mean_F1, n = 15)  # 取前15个

# 显示结果
print(top15_avg_groups)

# 取消分组
GeneBPBK_filter <- GeneBPBK %>% filter(GeneIdentify==95 & GeneLength==20 & GeneEvalue=="e1e5") %>% 
  filter(TrueValueIdentify==90&TrueValueCoverage==90,) %>% 
  filter(filter1=="f4_0.001.") %>% 
  filter(!(GeneKind == "ARGs" & TrueValueType == "anno")) %>% # 过滤ARGs
  filter(Level!="Kingdom")


datafram_melt <- reshape2::melt(GeneBPBK_filter,measure.vars = c(8:10,15:18))
datafram_melt$Level <- factor(datafram_melt$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
datafram_melt_se <- Rmisc::summarySE(datafram_melt, measurevar="value", groupvars=c("Level","GeneKind","variable","SpeciesNumbers"))

datafram_melt_se2 <- Rmisc::summarySE(datafram_melt, measurevar="value", groupvars=c("Level","GeneKind","variable","Info"))
datafram_melt_se2$Level <- factor(datafram_melt_se2$Level,level=c("Phylum","Class","Order","Family","Genus","Species"))
datafram_melt_se2$group <- paste0(datafram_melt_se2$Info)


Species=F
if (Species==T) {
  datafram_melt <- datafram_melt
  datafram_melt_se <- datafram_melt_se
  datafram_melt_se2 <- datafram_melt_se2
}else{
  datafram_melt <- datafram_melt %>% filter(Level!="Species")
  datafram_melt_se <- datafram_melt_se %>% filter(Level!="Species")
  datafram_melt_se2 <- datafram_melt_se2 %>% filter(Level!="Species")
}


ggplot()+
  # geom_point(aes(x = level,y = value,color=DB))+
  geom_jitter(data =datafram_melt, aes(x = Level,y = value),color="#33395d",alpha=.4,size=.3,show.legend = F,width = 0.1)+
  # geom_jitter(data =datafram_melt_se, aes(x = Level,y = value),color="#33395d",alpha=.2,show.legend = F)+
  # 第一条line虚线
  geom_line(data =datafram_melt,aes(x = Level,y = value,group=Sample),color="#33395d",size=.3,alpha=.6,show.legend = F)+
  # 第二条line实线
  geom_line(data =datafram_melt_se2,aes(x = Level,y = value,group=group),color="red",size=.5,alpha=.8,show.legend = F)+
  # geom_errorbar(data = datafram_melt_se2,aes(x = level,ymin=value-se, ymax=value+se), width=.1) +
  # geom_hline(yintercept = 0.6,linetype='dotted', col = 'red',size=1)+
  # geom_hline(yintercept = 0.5,linetype='dotted', col = 'blue',size=1)+
    # ✅ 添加误差线 (标准差)
  geom_errorbar(data = datafram_melt_se2,
                aes(x = Level, 
                    ymin = value - sd, 
                    ymax = value + sd, 
                    group = group),
                width = 0.2,
                size = 0.5,
                color = "red",
                alpha = 0.5,
                show.legend = FALSE) +
  facet_grid(GeneKind~variable)+
  theme_jgfbw()+xlab("")+ylab("")+
  scale_color_npg()+
  # scale_y_continuous(breaks = seq(0,1,0.25),labels = scales::percent,expand = c(0,0.025)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(legend.title = element_blank())+
  theme(legend.position = c(0.95,0.05),
        legend.key.size = unit(3, "pt"),
        legend.background = element_rect(fill="transparent"))

ggsave("03.figureUP/S_All_line_filter.pdf",height = 6,width = 8)

```

# 主图-最优阈值筛选
```{r}
# 筛选最优阈值——————————————————————————————————————————————————————
# BP-Tracer阈值：Identify==95 & Length==20 & Evalue=="e1e5"
# 丰度表阈值，按照 f4_0.001进行过滤
attach(AllBK)
AllBK_filter1 <- AllBK %>% filter(GeneIdentify==95 & GeneLength==20 & GeneEvalue=="e1e5") %>% 
  filter(TrueValueIdentify==90&TrueValueCoverage==90,) %>% 
  filter(filter1=="f4_0.001.") %>% 
  filter(!(GeneKind == "ARGs" & TrueValueType == "anno")) %>% # 过滤ARGs
  filter(Level!="Kingdom")

# MAGs和Cor的BenchMarker结果合并
AllBK2 <- bind_rows(MAGsBK2,CorBK2)
colnames(AllBK2)[2] <- "Level"
AllBK2 <- left_join(AllBK2,Group_TA,by=c("Sample"="ID"))
AllBK_filter2 <- AllBK2 %>% filter(Level!="Kingdom")

# 选取相对较高的分组进行分析吧
AllBK_filter <- rbind(AllBK_filter1,AllBK_filter2)
AllBK_filter$Group <- str_extract(AllBK_filter$Sample, "^T[34]")
temp <- AllBK_filter %>% select(Group,F1)
temp_avg <- aggregate(temp[,-1],by = list(temp[,1]),FUN = "mean")
cat("T3和T4两个Group的Bencmarker评估结果大概分布情况")
temp_avg

# 设置是否进行 T3 过滤的标志
filter_T3 <- FALSE  # 如果想过滤为T3组，设置为TRUE，否则设置为FALSE
# 根据 filter_T3 的值选择性进行过滤
AllBK_filter <- AllBK_filter %>%
  {if (filter_T3) filter(., Group == "T3") else .}

# 查看结果
# 数据可视化
datafram <- AllBK_filter %>%  dplyr::select(Sample,SpeciesNumbers,Level,Info,GeneKind,Method,Precision,Recall,F1,AbundancePrecision)
datafram_melt <- reshape2::melt(datafram,measure.vars = c(7:10))
datafram_melt$Level <- factor(datafram_melt$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
datafram_melt$variable <- factor(datafram_melt$variable,labels = c("Precision","Recall","F1 score","TP Rate"))

datafram_melt_se <- Rmisc::summarySE(datafram_melt, measurevar="value", groupvars=c("SpeciesNumbers","Level","GeneKind","Method","variable"))
datafram_melt_se$Level <- factor(datafram_melt_se$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
datafram_melt_se$group <- paste0(datafram_melt_se$SpeciesNumbers,datafram_melt_se$DB)

datafram_melt_se2 <- Rmisc::summarySE(datafram_melt, measurevar="value", groupvars=c("Level","GeneKind","Method","variable"))
datafram_melt_se2$Level <- factor(datafram_melt_se2$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
# datafram_melt_se2$group <- paste0(datafram_melt_se2$DB)

datafram_melt <- datafram_melt %>% filter(variable!="TP Rate")
datafram_melt_se <- datafram_melt_se %>% filter(variable!="TP Rate")
datafram_melt_se2 <- datafram_melt_se2 %>% filter(variable!="TP Rate")
unique(AllBK_filter$Method)

# 设置是否进行 Species过滤的标志
filter_Species <- F # 如果想过滤为T3组，设置为TRUE，否则设置为FALSE
# 根据 filter_T3 的值选择性进行过滤
datafram_melt <- datafram_melt %>%
  {if (filter_Species) filter(., Level != "Species") else .}
datafram_melt_se <- datafram_melt_se %>%
  {if (filter_Species) filter(., Level != "Species") else .}
datafram_melt_se2 <- datafram_melt_se2 %>%
  {if (filter_Species) filter(., Level != "Species") else .}
zyz_cols <-c("#8c2e2f","#33395d","#009399","#B877DD","#605d5c")
names(zyz_cols) <- c("BP-Tracer","Reads","Contigs","MAGs","Networks")

BK1 <- ggplot()+
  # geom_point(aes(x = Level,y = value,color=DB))+
  geom_jitter(data =datafram_melt, aes(x = Level,y = value,color=Method),alpha=.2,size=.4,show.legend = F)+
  # geom_point(data =datafram_melt_se, aes(x = Level,y = value,color=Method,shape=Method),alpha=.8,show.legend = F)+
  # 第一条line虚线
  geom_line(data =datafram_melt_se,aes(x = Level,y = value,group=Method,color=Method),size=.8,alpha=.7)+
  # 第二条line实线
  # geom_line(data =datafram_melt_se2,aes(x = Level,y = value,group=Method),color="red",size=.8,alpha=.5,show.legend = F)+
  geom_errorbar(data = datafram_melt_se2,aes(x = Level,ymin=value-sd, ymax=value+sd,color=Method), width=.1) +
  # geom_hline(yintercept = 0.75,linetype='dotted', col = 'red',size=1)+
  # geom_hline(yintercept = 0.5,linetype='dotted', col = 'blue',size=1)+
  facet_grid(variable~.)+
  facet_wrap(variable~.,ncol = 1)+
  theme_jgfbw()+xlab("")+ylab("Evaluation score")+
  scale_color_manual(values = zyz_cols)+
  scale_y_continuous(labels = scales::percent) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(legend.title = element_blank())+
  theme(legend.position = c(0.35,0.8),
        legend.key.size = unit(4, "pt"),
        legend.background = element_rect(fill="transparent"))
BK1
plot_name <- paste0("03.figureUP/M4_RG_line_filter.pdf")
ggsave(plot_name,height = 8,width = 3)




# 分科数据可视化
BK1_1 <- ggplot()+
  # geom_point(aes(x = Level,y = value,color=DB))+
  geom_jitter(data =datafram_melt[which(datafram_melt$variable=="Precision"),], aes(x = Level,y = value,color=Method),alpha=.2,size=.4,show.legend = F)+
  geom_point(data =datafram_melt_se[which(datafram_melt_se$variable=="Precision"),], aes(x = Level,y = value,color=Method,shape=Method),alpha=.8,show.legend = F)+
  # 第一条line虚线
  geom_line(data =datafram_melt_se[which(datafram_melt_se$variable=="Precision"),],aes(x = Level,y = value,group=Method,color=Method),size=.8,alpha=.7)+
  # 第二条line实线
  # geom_line(data =datafram_melt_se2,aes(x = Level,y = value,group=Method),color="red",size=.8,alpha=.5,show.legend = F)+
  geom_errorbar(data = datafram_melt_se2[which(datafram_melt_se2$variable=="Precision"),],aes(x = Level,ymin=value-sd, ymax=value+sd,color=Method), width=.1) +
  facet_grid(variable~.)+
  facet_wrap(variable~.,ncol = 1)+
  theme_jgfbw()+xlab("")+ylab("")+
  scale_color_manual(values = zyz_cols)+
  scale_y_continuous(limits = c(0,1),breaks = seq(0,1,0.25),labels = scales::percent,expand = c(0,0.025)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(legend.title = element_blank())+
  theme(legend.position = c(0.34,0.1),
        legend.key.size = unit(10, "pt"),
        legend.background = element_rect(fill="transparent"))+
   guides(color=guide_legend(nrow =1))+
   theme(axis.ticks.x = element_blank(),axis.text.x = element_blank())     #关闭x轴刻度和标签
BK1_1

BK1_2 <- ggplot()+
  # geom_point(aes(x = Level,y = value,color=DB))+
  geom_jitter(data =datafram_melt[which(datafram_melt$variable=="Recall"),], aes(x = Level,y = value,color=Method),alpha=.2,size=.4,show.legend = F)+
  geom_point(data =datafram_melt_se[which(datafram_melt_se$variable=="Recall"),], aes(x = Level,y = value,color=Method,shape=Method),alpha=.8,show.legend = F)+
  # 第一条line虚线
  geom_line(data =datafram_melt_se[which(datafram_melt_se$variable=="Recall"),],aes(x = Level,y = value,group=Method,color=Method),size=.8,alpha=.7,show.legend = F)+
  # 第二条line实线
  # geom_line(data =datafram_melt_se2,aes(x = Level,y = value,group=Method),color="red",size=.8,alpha=.5,show.legend = F)+
  geom_errorbar(data = datafram_melt_se2[which(datafram_melt_se2$variable=="Recall"),],aes(x = Level,ymin=value-sd, ymax=value+sd,color=Method), width=.1,show.legend = F) +
  facet_grid(variable~.)+
  facet_wrap(variable~.,ncol = 1)+
  theme_jgfbw()+xlab("")+ylab("Evaluation score")+
  scale_color_manual(values = zyz_cols)+
  scale_y_continuous(limits = c(0,1),breaks = seq(0,1,0.25),labels = scales::percent,expand = c(0,0.025)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(legend.title = element_blank())+
  theme(legend.position = "none",
        legend.key.size = unit(4, "pt"),
        legend.background = element_rect(fill="transparent"))+
   theme(axis.ticks.x = element_blank(),axis.text.x = element_blank())     #关闭x轴刻度和标签
BK1_2

BK1_3 <- ggplot()+
  # geom_point(aes(x = Level,y = value,color=DB))+
  geom_jitter(data =datafram_melt[which(datafram_melt$variable=="F1 score"),], aes(x = Level,y = value,color=Method),alpha=.2,size=.4,show.legend = F)+
  geom_point(data =datafram_melt_se[which(datafram_melt_se$variable=="F1 score"),], aes(x = Level,y = value,color=Method,shape=Method),alpha=.8,show.legend = F)+
  # 第一条line虚线
  geom_line(data =datafram_melt_se[which(datafram_melt_se$variable=="F1 score"),],aes(x = Level,y = value,group=Method,color=Method),size=.8,alpha=.7,show.legend = F)+
  # 第二条line实线
  # geom_line(data =datafram_melt_se2,aes(x = Level,y = value,group=Method),color="red",size=.8,alpha=.5,show.legend = F)+
  geom_errorbar(data = datafram_melt_se2[which(datafram_melt_se2$variable=="F1 score"),],aes(x = Level,ymin=value-sd, ymax=value+sd,color=Method), width=.1,show.legend = F) +
  facet_grid(variable~.)+
  facet_wrap(variable~.,ncol = 1)+
  theme_jgfbw()+xlab("")+ylab("")+
  scale_color_manual(values = zyz_cols)+
  scale_y_continuous(limits = c(0,1),breaks = seq(0,1,0.25),labels = scales::percent,expand = c(0,0.025)) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(legend.title = element_blank())+
  theme(legend.position = "none",
        legend.key.size = unit(4, "pt"),
        legend.background = element_rect(fill="transparent"))
   # theme(axis.ticks.x = element_blank(),axis.text.x = element_blank())     #关闭x轴刻度和标签
BK1_3

```


# 主图-BK的F1value
```{r}
attach(AllBK_filter)
head(AllBK_filter)

AllBK_filter <- AllBK_filter #%>% filter(Group=="T3")
# 数据统计情况
dfF1 <- AllBK_filter %>%  dplyr::select(Sample,SpeciesNumbers,Level,Info,GeneKind,Method,Precision,Recall,F1,Spearman)
dfF1_melt <- reshape2::melt(dfF1,measure.vars = c(7:10))
dfF1_melt$Level <- factor(dfF1_melt$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
dfF1_melt <- dfF1_melt %>% filter(Level!="Species")
dfF1_melt$variable <- factor(dfF1_melt$variable,labels = c("Precision","Recall","F1 score","Spearman"))

# 计算平均值标准差
dfF1_melt_se <- Rmisc::summarySE(dfF1_melt, measurevar="value", groupvars=c("SpeciesNumbers","Level","GeneKind","Method","variable"))
dfF1_melt_se$Level <- factor(dfF1_melt_se$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
dfF1_melt_se$group <- paste0(dfF1_melt_se$SpeciesNumbers,dfF1_melt_se$DB)

# 计算平均值
dfF1_melt_se2 <- Rmisc::summarySE(dfF1_melt, measurevar="value", groupvars=c("Level","GeneKind","Method","variable"))
dfF1_melt_se2$Level <- factor(dfF1_melt_se2$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )

zyz_cols <-c("#8c2e2f","#33395d","#009399","#B877DD","#605d5c")
names(zyz_cols) <- c("BP-Tracer","Reads","Contigs","MAGs","Networks")

BK1_F1 <- ggplot()+
  # geom_point(aes(x = Level,y = value,color=DB))+
  geom_jitter(data =dfF1_melt, aes(x = Level,y = value,color=Method),alpha=.2,size=.4,show.legend = F)+
  geom_point(data =dfF1_melt_se, aes(x = Level,y = value,color=Method,shape=Method),alpha=.8,show.legend = F)+
  # 第一条line虚线
  geom_line(data =dfF1_melt_se,aes(x = Level,y = value,group=Method,color=Method),size=.8,alpha=.7)+
  # 第二条line实线
  # geom_line(data =dfF1_melt_se2,aes(x = Level,y = value,group=Method),color="red",size=.8,alpha=.5,show.legend = F)+
  geom_errorbar(data = dfF1_melt_se2,aes(x = Level,ymin=value-sd, ymax=value+sd,color=Method), width=.1) +
  # geom_hline(yintercept = 0.75,linetype='dotted', col = 'red',size=1)+
  # geom_hline(yintercept = 0.5,linetype='dotted', col = 'blue',size=1)+
  # facet_grid(variable~.)+
  facet_wrap(variable~.,ncol = 1,scales = "free_y")+
  theme_jgfbw()+xlab("")+ylab("Evaluation score")+
  scale_color_manual(values = zyz_cols)+
  # scale_y_continuous(labels = scales::percent) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(legend.title = element_blank())+
  theme(legend.position = c(0.35,0.8),
        legend.key.size = unit(4, "pt"),
        legend.background = element_rect(fill="transparent"))


BK1_F1


```

# 统计-BK的F1指标
```{r}
attach(datafram_melt_se2)
cat("Bencmarker中BP-Tracer的F1指标：", "\n")
# 转换成百分比并保留两位小数
datafram_melt_se2 %>%
  filter(Method == "BP-Tracer", variable == "F1 score") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中BP-Tracer的Recall指标：", "\n")
datafram_melt_se2 %>%
  filter(Method == "BP-Tracer", variable == "Recall") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中BP-Tracer的Precision指标：", "\n")
datafram_melt_se2 %>%
  filter(Method == "BP-Tracer", variable == "Precision") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

```

# 主图-BK的Beta
```{r}
attach(AllBK_filter)
head(AllBK_filter)

# 数据统计情况
dfBeta <- AllBK_filter %>%  dplyr::select(Sample,SpeciesNumbers,Level,Info,GeneKind,Method,L1,L2,BC,rJSD)
dfBeta_melt <- reshape2::melt(dfBeta,measure.vars = c(7:10))
dfBeta_melt$Level <- factor(dfBeta_melt$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
dfBeta_melt <- dfBeta_melt %>% filter(Level!="Species")
dfBeta_melt$variable <- factor(dfBeta_melt$variable,labels = c("L1","L2","Bray–Curtis (BC)","rJSD"))

# 计算平均值标准差
dfBeta_melt_se <- Rmisc::summarySE(dfBeta_melt, measurevar="value", groupvars=c("SpeciesNumbers","Level","GeneKind","Method","variable"))
dfBeta_melt_se$Level <- factor(dfBeta_melt_se$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )
dfBeta_melt_se$group <- paste0(dfBeta_melt_se$SpeciesNumbers,dfBeta_melt_se$DB)

# 计算平均值
dfBeta_melt_se2 <- Rmisc::summarySE(dfBeta_melt, measurevar="value", groupvars=c("Level","GeneKind","Method","variable"))
dfBeta_melt_se2$Level <- factor(dfBeta_melt_se2$Level,levels=c("Phylum","Class","Order","Family","Genus","Species") )

# 配色设计 B877DD

zyz_cols <-c("#8c2e2f","#33395d","#009399","#B877DD","#605d5c")
names(zyz_cols) <- c("BP-Tracer","Reads","Contigs","MAGs","Networks")

BK1_beta <- ggplot()+
  # geom_point(aes(x = Level,y = value,color=DB))+
  geom_jitter(data =dfBeta_melt, aes(x = Level,y = value,color=Method),alpha=.2,size=.4,show.legend = F)+
  geom_point(data =dfBeta_melt_se, aes(x = Level,y = value,color=Method,shape=Method),alpha=.8,show.legend = F)+
  # 第一条line虚线
  geom_line(data =dfBeta_melt_se,aes(x = Level,y = value,group=Method,color=Method),size=.8,alpha=.7)+
  # 第二条line实线
  # geom_line(data =dfBeta_melt_se2,aes(x = Level,y = value,group=Method),color="red",size=.8,alpha=.5,show.legend = F)+
  geom_errorbar(data = dfBeta_melt_se2,aes(x = Level,ymin=value-sd, ymax=value+sd,color=Method), width=.1) +
  # geom_hline(yintercept = 0.75,linetype='dotted', col = 'red',size=1)+
  # geom_hline(yintercept = 0.5,linetype='dotted', col = 'blue',size=1)+
  # facet_grid(variable~.)+
  facet_wrap(variable~.,ncol = 1,scales = "free_y")+
  theme_jgfbw()+xlab("")+ylab("Evaluation score")+
  scale_color_manual(values = zyz_cols)+
  # scale_y_continuous(labels = scales::percent) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(legend.title = element_blank())+
  theme(legend.position = c(0.35,0.8),
        legend.key.size = unit(4, "pt"),
        legend.background = element_rect(fill="transparent"))
BK1_beta


library(ggplot2)

plot_variable <- function(datafram_melt, datafram_melt_se, datafram_melt_se2, 
                          variable_name, zyz_cols, 
                          show_x_text = TRUE, show_legend = FALSE,
                          show_percent = TRUE, y_limits = c(0, 1)) {
  
  p <- ggplot() +
    # 散点（抖动）
    geom_jitter(
      data = datafram_melt[datafram_melt$variable == variable_name, ],
      aes(x = Level, y = value, color = Method),
      alpha = .2, size = .4, show.legend = FALSE
    ) +
    # 平均点
    geom_point(
      data = datafram_melt_se[datafram_melt_se$variable == variable_name, ],
      aes(x = Level, y = value, color = Method, shape = Method),
      alpha = .8, show.legend = FALSE
    ) +
    # 第一条虚线
    geom_line(
      data = datafram_melt_se[datafram_melt_se$variable == variable_name, ],
      aes(x = Level, y = value, group = Method, color = Method),
      show.legend = FALSE,
      size = .8, alpha = .7
    ) +
    # 误差条
    geom_errorbar(
      data = datafram_melt_se2[datafram_melt_se2$variable == variable_name, ],
      aes(x = Level, ymin = value - sd, ymax = value + sd, color = Method),
      show.legend = FALSE,
      width = .1
    ) +
    theme_jgfbw() +
    xlab("") + ylab(variable_name) +
    scale_color_manual(values = zyz_cols) +
    scale_y_continuous(
      limits = y_limits,
      breaks = seq(y_limits[1], y_limits[2], length.out = 5),
      labels = if (show_percent) scales::percent else scales::number,
      expand = c(0, 0.025)
    ) +
    theme(
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank(),
      plot.margin =  ggplot2::margin(t = 0, r = 0, b = 0, l = 5, unit = "mm"),
      legend.margin =  ggplot2::margin(t = 0, r = 0, b = 0, l = 0, unit = "mm")
    )
  
  # 控制是否显示 x 轴文字
  if (show_x_text) {
    p <- p + theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))
  } else {
    p <- p + theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
  }
  
  # 控制是否显示图例
  if (show_legend) {
    p <- p + theme(
      legend.position = c(0.34, 0.1),
      legend.key.size = unit(10, "pt"),
      legend.background = element_rect(fill = "transparent")
    ) +
      guides(color = guide_legend(nrow = 1))
  } else {
    p <- p + theme(legend.position = "none")
  }
  
  return(p)
}



P_Pre <- plot_variable(datafram_melt = dfF1_melt,datafram_melt_se = dfF1_melt_se,datafram_melt_se2 = dfF1_melt_se2,variable_name = "Precision",zyz_cols = zyz_cols,show_x_text = T ,show_legend = T)

P_Rec <- plot_variable(datafram_melt = dfF1_melt,datafram_melt_se = dfF1_melt_se,datafram_melt_se2 = dfF1_melt_se2,variable_name = "Recall",zyz_cols = zyz_cols,show_x_text = T,show_legend = F)

P_F1 <- plot_variable(datafram_melt = dfF1_melt,datafram_melt_se = dfF1_melt_se,datafram_melt_se2 = dfF1_melt_se2,variable_name = "F1 score",zyz_cols = zyz_cols,show_x_text = T,show_legend = F)

P_L1 <- plot_variable(datafram_melt = dfBeta_melt,datafram_melt_se = dfBeta_melt_se,datafram_melt_se2 = dfBeta_melt_se2,variable_name = "L1",zyz_cols = zyz_cols,show_x_text = T,show_legend = F,show_percent = F,y_limits = c(0,2))
P_L1

P_L2 <- plot_variable(datafram_melt = dfBeta_melt,datafram_melt_se = dfBeta_melt_se,datafram_melt_se2 = dfBeta_melt_se2,variable_name = "L2",zyz_cols = zyz_cols,show_x_text = T,show_legend = F,y_limits = c(0,1))
P_L2

P_BC <- plot_variable(datafram_melt = dfBeta_melt,datafram_melt_se = dfBeta_melt_se,datafram_melt_se2 = dfBeta_melt_se2,variable_name = "Bray–Curtis (BC)",zyz_cols = zyz_cols,show_x_text = T,show_legend = F,y_limits = c(0,1))
P_BC

P_rJSD <- plot_variable(datafram_melt = dfBeta_melt,datafram_melt_se = dfBeta_melt_se,datafram_melt_se2 = dfBeta_melt_se2,variable_name = "rJSD",zyz_cols = zyz_cols,show_x_text = T,show_legend = F)
P_rJSD

```

#统计-BK的Beta指标
```{r}
attach(dfBeta_melt_se2)
cat("Bencmarker中BP-Tracer的L1指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "BP-Tracer", variable == "L1") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中BP-Tracer的L2指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "BP-Tracer", variable == "L2") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中BP-Tracer的BC指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "BP-Tracer", variable == "Bray–Curtis (BC)") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中BP-Tracer的rJSD指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "BP-Tracer", variable == "rJSD") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)


# Reads
cat("Bencmarker中Reads的L1指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Reads", variable == "L1") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中Reads的L2指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Reads", variable == "L2") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中Reads的BC指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Reads", variable == "Bray–Curtis (BC)") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中Reads的rJSD指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Reads", variable == "rJSD") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)


# Contigs
cat("Bencmarker中Contigs的L1指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Contigs", variable == "L1") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中BP-Tracer的L2指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Contigs", variable == "L2") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)

cat("Bencmarker中Contigs的BC指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Contigs", variable == "Bray–Curtis (BC)") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)
cat("Bencmarker中Contigs的rJSD指标：", "\n")
dfBeta_melt_se2 %>%
  filter(Method == "Contigs", variable == "rJSD") %>%
  mutate(value_percent = round(value * 100, 2)) %>%  
  select(Level, value_percent)


```


# 主图-BK的序列利用率计算
```{r}
# 读取RawContigs文件
# 文件list读取
all.files = list.files(path = "01.rawdata/BP2_BK/06.MethodStat/rawContigs",full.name = T,pattern = ".stat") ### od文件目录 ###
# 设置空数据集
RawContigs_stat =data.frame(stringsAsFactors = F) 
# 循环批量读入文件
i=all.files[1]
for (i in all.files) {
  data <- read.delim(i,header = F,sep = "\t",quote = "",check.names = F)
  dataName1 <- stringr::str_split(string = i,pattern = '\\/',simplify = T)[1,5]
  dataName2 <- stringr::str_split(string = dataName1,pattern = "\\.stat",simplify =T)[1,1]
  colnames(data) <- c("variable","Index")
  data$name <- dataName2
  data$variable <- stringr::str_replace(string = data$variable,pattern = ":",replacement = "")
  data_short <- tidyr::spread(data,key = variable,value = Index)
  RawContigs_stat = rbind(RawContigs_stat,data_short)
}


# 读取RawReads文件
# 文件list读取
all.files = list.files(path = "01.rawdata/BP2_BK/06.MethodStat/RawReads",full.name = T,pattern = ".stat") ### od文件目录 ###
# 设置空数据集
RawReads_stat =data.frame(stringsAsFactors = F) 
# 循环批量读入文件
i=all.files[1]
for (i in all.files) {
  data <- read.delim(i,header = F,sep = "\t",quote = "",check.names = F)
  dataName1 <- stringr::str_split(string = i,pattern = '\\/',simplify = T)[1,5]
  dataName2 <- stringr::str_split(string = dataName1,pattern = "\\.stat",simplify =T)[1,1]
  colnames(data) <- c("variable","Index")
  data$name <- dataName2
  data$variable <- stringr::str_replace(string = data$variable,pattern = ":",replacement = "")
  data_short <- tidyr::spread(data,key = variable,value = Index)
  RawReads_stat = rbind(RawReads_stat,data_short)
}


BP_stat <- read.delim(file = "01.rawdata/BP2_BK/06.MethodStat/BP/filtered_blast.final.stat",check.names = F,header = F)
colnames(BP_stat) <- c("ID","SequenceNumber","File")
BP_stat$Method <- "BP-Tracer"

Reads_stat <- read.delim(file = "01.rawdata/BP2_BK/06.MethodStat/Reads/filtered_blast.final.stat",check.names = F,header = F)
colnames(Reads_stat) <- c("ID","SequenceNumber","File")
Reads_stat$Method <- "Reads"

Contigs_stat <- read.delim(file = "01.rawdata/BP2_BK/06.MethodStat/Contigs/filtered_blast.final.stat",check.names = F,header = F)
colnames(Contigs_stat) <- c("ID","SequenceNumber","File")
Contigs_stat$Method <- "Contigs"


# 序列利用率可视化-----
attach(Reads_stat)
attach(Contigs_stat)
attach(BP_stat)

attach(RawContigs_stat)
attach(RawReads_stat)

# Reads统计数据
RawReads_stat2 <- RawReads_stat
RawReads_stat2$ID <- str_extract(RawReads_stat2$name, "^[A-Z0-9-]+")
RawReads_stat2 <- RawReads_stat2 %>% dplyr::select(ID,"Total number")
RawReads_stat2$`Total number` <- as.numeric(RawReads_stat2$`Total number`)
RawReads_stat_fianl <- RawReads_stat2 %>% group_by(ID) %>%  summarise_if(is.numeric, ~ sum(., na.rm = F))  
colnames(RawReads_stat_fianl)[2] <- "RawReadsNum"

# Contigs统计数据
RawContigs_stat2 <- RawContigs_stat
RawContigs_stat2$ID <- str_extract(RawContigs_stat2$name, "^[A-Z0-9-]+")
RawContigs_stat2 <- RawContigs_stat2 %>%  dplyr::select(ID,`Total number`)
RawContigs_stat2$`Total number` <- as.numeric(RawContigs_stat2$`Total number`)
RawContigs_stat_final <- RawContigs_stat2
colnames(RawContigs_stat_final)[2] <- "RawReadsNum"


# 这里就用整体的RawReads_Stat 用于计算整体的序列利用率
Reads_use <- rbind(
left_join(Reads_stat,RawReads_stat_fianl),
left_join(BP_stat,RawReads_stat_fianl),
# left_join(Contig_stat,RawContigs_stat2_final)
left_join(Contigs_stat,RawReads_stat_fianl)
)

Reads_use <- left_join(Reads_use,Group_TA)
Reads_use$Reads_utilization_rate <- Reads_use$SequenceNumber/Reads_use$RawReadsNum
Reads_use_filter <- Reads_use %>% filter(File %in% "filtered_blast.i95.l20.e1e-5.stat" ) 


Reads_use_filter[nrow(Reads_use_filter)+1,] <- NA;Reads_use_filter$Method[is.na(Reads_use_filter$Method)] <- "MAGs"
Reads_use_filter[nrow(Reads_use_filter)+1,] <- NA;Reads_use_filter$Method[is.na(Reads_use_filter$Method)] <- "Correlation"
Reads_use_filter$Method <- factor(Reads_use_filter$Method,levels = c("BP-Tracer","Reads","Contigs","MAGs","Correlation"))
Reads_use_filter$temp <- "ARG detection efficiency"




# 数据分析以及可视化
# 显著性差异分析
library(LorMe)

Reads_use_filter_na <- Reads_use_filter[which(!is.na(Reads_use_filter$ID) ),]
ReadsNum <- LorMe::auto_signif_test(data = Reads_use_filter_na, treatment_col = 4,value_col = 2)
ReadsFreq <- LorMe::auto_signif_test(data = Reads_use_filter_na, treatment_col = 4,value_col = 10)
ReadsFreq$muiltiple_comparision_model

num_for_value <- 0.000001
y1 <- Reads_use_filter %>% filter(Method=="Reads") %>% dplyr::select(Reads_utilization_rate); y1_value <- max(y1$Reads_utilization_rate)+num_for_value
y2 <- Reads_use_filter %>% filter(Method=="Contigs") %>% dplyr::select(Reads_utilization_rate); y2_value <- max(y2$Reads_utilization_rate)+num_for_value
y3 <- Reads_use_filter %>% filter(Method=="MAGs") %>% dplyr::select(Reads_utilization_rate); y3_value <- max(y3$Reads_utilization_rate)+num_for_value
y4 <- Reads_use_filter %>% filter(Method=="Correlation") %>% dplyr::select(Reads_utilization_rate); y4_value <- max(y4$Reads_utilization_rate)+num_for_value

z1 <- Reads_use_filter %>% filter(Method=="Reads") %>% dplyr::select(SequenceNumber); z1_value <- max(z1$SequenceNumber)+num_for_value
z2 <- Reads_use_filter %>% filter(Method=="Contigs") %>% dplyr::select(SequenceNumber); z2_value <- max(z2$SequenceNumber)+num_for_value
z3 <- Reads_use_filter %>% filter(Method=="MAGs") %>% dplyr::select(SequenceNumber); z3_value <- max(z3$SequenceNumber)+num_for_value
z4 <- Reads_use_filter %>% filter(Method=="Correlation") %>% dplyr::select(SequenceNumber); z4_value <- max(z4$SequenceNumber)+num_for_value




y3_value <- min(y2$Reads_utilization_rate)
y4_value <- min(y2$Reads_utilization_rate)

z3_value <- min(z2$SequenceNumber)
z4_value <- min(z2$SequenceNumber)

stars_data <- data.frame(
  Group =  c("Reads","Contigs","MAGs","Correlation"),
  Value = c(y1_value, y2_value, y3_value,y4_value),  # 设置星星的垂直位置
  Label = c("****", "****", "NA","NA")  # 星星标记
)

stars_data2 <- data.frame(
  Group =  c("MAGs","Correlation"),
  Value = c(y3_value,y4_value),  # 设置星星的垂直位置
  Label = c("NA","NA")  # 星星标记
)

stars_data3 <- data.frame(
  Group =  c("MAGs","Correlation"),
  Value = c(z3_value,z4_value),  # 设置星星的垂直位置
  Label = c("NA","NA")  # 星星标记
)

Reads_use_filter2 <- Reads_use_filter  %>% filter(Group!="T4")
zyz_cols <-c("#8c2e2f","#33395d","#009399","#B877DD","#605d5c")
names(zyz_cols) <- c("BP-Tracer","Reads","Contigs","MAGs","Correlation")
my_comparison=list(c("Reads","Contigs"),c("Reads","BP-Tracer"),c("BP-Tracer","Contigs")) #定义比较的分组

P_Seq_raw <- ggplot(data = Reads_use_filter,aes(x = Method,y = Reads_utilization_rate,color=Method))+
  theme_jgfbw()+
  scale_color_manual(values = zyz_cols)+
  # geom_violin(width=1,size = .5,alpha=0.9,position = position_dodge(.5)) +
  geom_boxplot(width=0.5,size = .2,alpha=0.7,outlier.size=0,coef=1,# coef control the IQR
               position = position_dodge(.5),show.legend = F) +
  geom_point(alpha=.3,show.legend = F)+
  geom_line(aes(group=ID), color="gray" ,size=.2,alpha=.4,show.legend = F) +
  facet_wrap(~temp)+
  theme(legend.position = "none")+
  # theme(axis.title.x=element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  # scale_y_continuous(labels = scales::percent) +
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",bracket.size=0,vjust = .7,size=3,label = "p.signif")+
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",vjust = .7,label = "p.signif")+
  xlab("")+ylab("")+
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  # theme(axis.ticks.x = element_blank(),axis.text.x = element_blank())  +
  geom_text(data = stars_data,color="black", aes(x = Group, y = Value, label = Label),
              size = 4, vjust = -1)  # 调整垂直位置
  # ggtitle(subtitle = "Reads Utilization Rate")+
  # theme(plot.title = element_text( face = "bold"))
P_Seq_raw

P_Seq_raw2 <- ggplot(data = Reads_use_filter,aes(x = Method,y = Reads_utilization_rate,color=Method))+
  theme_jgfbw()+
  scale_color_manual(values = zyz_cols)+
  # geom_violin(width=1,size = .5,alpha=0.9,position = position_dodge(.5)) +
  geom_boxplot(width=0.5,size = .2,alpha=0.7,outlier.size=0,coef=1,# coef control the IQR
               position = position_dodge(.5),show.legend = F) +
  geom_point(alpha=.3,show.legend = F)+
  geom_line(aes(group=ID), color="gray" ,size=.2,alpha=.4,show.legend = F) +
  # theme(legend.position = "none")+
  # theme(axis.title.x=element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  # scale_y_continuous(labels = scales::percent) +
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",bracket.size=0,vjust = .7,size=3,label = "p.signif")+
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",vjust = .7,label = "p.signif")+
  xlab("")+ylab("Alignment rate")+
  # theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5),
  #             plot.margin = margin(0, 0, 0, 5, "mm"))+
  # theme(axis.ticks.x = element_blank(),axis.text.x = element_blank())  +
  geom_text(data = stars_data,color="black", aes(x = Group, y = Value, label = Label),
              size = 4, vjust = -1)  # 调整垂直位置
  # ggtitle(subtitle = "Reads Utilization Rate")+
  # theme(plot.title = element_text( face = "bold"))
P_Seq_raw2


P_SeqFreq <- ggplot(data = Reads_use_filter, aes(x = Method, y = Reads_utilization_rate, color = Method)) +
  theme_jgfbw() +
  scale_color_manual(values = zyz_cols) +
  geom_boxplot(width = 0.5, size = .2, alpha = 0.7, outlier.size = 0, coef = 1,
               position = position_dodge(.5), show.legend = F) +
  geom_point(alpha = .3, show.legend = F) +
  geom_line(aes(group = ID), color = "gray", size = .2, alpha = .4, show.legend = F) +
  xlab("") + ylab("ARG detection efficiency") +

  # 添加两两比较的统计检验
  stat_compare_means(
    comparisons = list(
      c("BP-Tracer", "Reads"),
      c("BP-Tracer", "Contigs")
    ),
    method = "t.test",
    paired = TRUE,  # 根据您的数据是否为配对样本设置
    label = "p.signif",  # 显示显著性符号 (*, **, ***)
    bracket.size = 0.5,  # 调整括号大小
    tip.length = 0.02,   # 调整提示线长度
    vjust = 0.5,         # 调整标签垂直位置
    size = 3             # 调整标签字体大小
  )+
  geom_text(data = stars_data2,color="black", aes(x = Group, y = Value, label = Label),
              size = 4, vjust = -1)+  # 调整垂直位置
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5),
              plot.margin = ggplot2::margin(0, 0, 0, 5, "mm"))

P_SeqFreq


P_SeqNum <- ggplot(data = Reads_use_filter, aes(x = Method, y = SequenceNumber, color = Method)) +
  theme_jgfbw() +
  scale_color_manual(values = zyz_cols) +
  geom_boxplot(width = 0.5, size = .2, alpha = 0.7, outlier.size = 0, coef = 1,
               position = position_dodge(.5), show.legend = F) +
  geom_point(alpha = .3, show.legend = F) +
  geom_line(aes(group = ID), color = "gray", size = .2, alpha = .4, show.legend = F) +
  xlab("") + ylab("ARGs detection number") +
  
  # 添加两两比较的统计检验
  stat_compare_means(
    comparisons = list(
      c("BP-Tracer", "Reads"),
      c("BP-Tracer", "Contigs")
    ),
    method = "t.test",
    paired = TRUE,  # 根据您的数据是否为配对样本设置
    label = "p.signif",  # 显示显著性符号 (*, **, ***)
    bracket.size = 0.5,  # 调整括号大小
    tip.length = 0.02,   # 调整提示线长度
    vjust = 0.5,         # 调整标签垂直位置
    size = 3             # 调整标签字体大小
  )+
  geom_text(data = stars_data3,color="black", aes(x = Group, y = Value, label = Label),
              size = 4, vjust = -1)+  # 调整垂直位置
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5),
              plot.margin = ggplot2::margin(0, 0, 0, 5, "mm"))

P_SeqNum

```
# 主图-BK的TPNum和ReadsPrecision
```{r}

attach(AllBK_filter)
pre_Gene_final_Num <- AllBK_filter
pre_Gene_final_Num$temp <- "TP Species Numbers"
pre_Gene_final_Num$Method <- factor(pre_Gene_final_Num$Method,levels = c("BP-Tracer","Reads","Contigs","MAGs","Networks"))
colnames(pre_Gene_final_Num)[4] <- "TPSpecies"

# 创建一个包含星星标记的数据框
Level="Species"
num_for_value <- 5
y1 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="Reads") %>% dplyr::select(TPSpecies); y1_value <- max(y1$TPSpecies)+num_for_value
y2 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="Contigs") %>% dplyr::select(TPSpecies); y2_value <- max(y2$TPSpecies)+num_for_value
y3 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="MAGs") %>% dplyr::select(TPSpecies); y3_value <- max(y3$TPSpecies)+num_for_value
y4 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="Networks") %>% dplyr::select(TPSpecies); y4_value <- max(y4$TPSpecies)+num_for_value



stars_data <- data.frame(
  Group =  c("Reads","Contigs","MAGs","Networks"),
  Value = c(y1_value, y2_value, y3_value,y4_value),  # 设置星星的垂直位置
  Label = c("****", "****", "****","NA")  # 星星标记
)

pre_Gene_final_Num <- pre_Gene_final_Num %>% filter(Level=="Species")
my_comparison=list(c("BP-Tracer","Reads"),c("BP-Tracer","Contigs"),c("BP-Tracer","MAGs"),c("BP-Tracer","Networks")) #定义比较的分组
BK3 <- ggplot(data = pre_Gene_final_Num,aes(x = Method,y = TPSpecies,color=Method))+
  theme_jgfbw()+
  scale_color_manual(values = zyz_cols)+
  # geom_violin(width=1,size = .5,alpha=0.9,position = position_dodge(.5)) +
  geom_boxplot(width=0.5,size = .2,alpha=0.7,outlier.size=0,coef=1,# coef control the IQR
               position = position_dodge(.5),show.legend = F) +
  geom_point(alpha=.2,show.legend = F)+
  geom_line(aes(group=Sample), color="gray" ,size=.2,alpha=.4,show.legend = F) +
  facet_wrap(~temp)+
  theme(legend.position = "none")+
  # theme(axis.title.x=element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",bracket.size=0,vjust = .7,size=3,label = "p.signif")+
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",vjust = .7,label = "p.signif",label.x = c(1,2,3,4,5))+
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",vjust = .7,label = "p.signif")+
  xlab("")+ylab("")+
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))+
  theme(axis.ticks.x = element_blank(),axis.text.x = element_blank()) 
  # geom_text(data = stars_data,color="black", aes(x = Group, y = Value, label = Label),size = 4, vjust = -1)  # 调整垂直位置
  # ggtitle(subtitle = "Reads Utilization Rate")+
  # theme(plot.title = element_text( face = "bold"))
BK3


attach(AllBK_filter)
pre_Gene_final_Rate <- AllBK_filter
pre_Gene_final_Rate$temp <- "TP Relative abundance"
my_comparison=list(c("Reads","Contigs"),c("Reads","BP-Tracer"),c("BP-Tracer","Contigs")) #定义比较的分组
pre_Gene_final_Rate$Method <- factor(pre_Gene_final_Rate$Method,levels = c("BP-Tracer","Reads","Contigs","MAGs","Networks"))



num_for_value <- 0.001
y1 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="Reads") %>% dplyr::select(AbundancePrecision); y1_value <- max(y1$AbundancePrecision)+num_for_value
y2 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="Contigs") %>% dplyr::select(AbundancePrecision); y2_value <- max(y2$AbundancePrecision)+num_for_value
y3 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="MAGs") %>% dplyr::select(AbundancePrecision); y3_value <- max(y3$AbundancePrecision)+num_for_value
y4 <- pre_Gene_final_Num %>% filter(Level=="Species",Method=="Networks") %>% dplyr::select(AbundancePrecision); y4_value <- max(y4$AbundancePrecision)+num_for_value

y3_value <- min(y1$AbundancePrecision)
y4_value <- min(y1$AbundancePrecision)

stars_data <- data.frame(
  Group =  c("Reads","Contigs","MAGs","Correlation"),
  Value = c(y1_value, y2_value, y3_value,y4_value),  # 设置星星的垂直位置
  Label = c("****", "****", "NA","NA")  # 星星标记
)


pre_Gene_final_Rate <- pre_Gene_final_Rate %>% filter(Level=="Species")
my_comparison=list(c("Reads","Contigs"),c("Reads","BP-Tracer"),c("BP-Tracer","Contigs"),c("MAGs","Contigs")) #定义比较的分组
BK4 <- ggplot(data =( pre_Gene_final_Rate),aes(x = Method,y = AbundancePrecision,color=Method))+
  theme_jgfbw()+
  scale_color_manual(values = zyz_cols)+
  # geom_violin(width=1,size = .5,alpha=0.9,position = position_dodge(.5)) +
  geom_boxplot(width=0.5,size = .2,alpha=0.7,outlier.size=0,coef=1,# coef control the IQR
               position = position_dodge(.5),show.legend = F) +
  geom_point(alpha=.4,show.legend = F)+
  geom_line(aes(group=Sample), color="gray" ,size=.2,alpha=.4,show.legend = F) +
  theme(legend.position = "none")+
  # scale_y_continuous(limits = c(0.3,0.65),labels = scales::percent) + 
  # theme(axis.title.x=element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",bracket.size=0,vjust = .7,size=3,label = "p.signif")+
  # stat_compare_means(comparisons = my_comparison,paired = T,method = "t.test",vjust = .7,label = "p.signif",label.y = c(0.6,0.65,0.7))+
  xlab("")+ylab("")+
  theme(axis.text.x = element_text(angle = 45, hjust = 0.2, vjust = 0.5))+
  theme(axis.ticks.x = element_blank(),axis.text.x = element_blank())  +
  geom_text(data = stars_data,color="black", aes(x = Group, y = Value, label = Label),
              size = 4, vjust = -1)  # 调整垂直位置
  # ggtitle(subtitle = "Reads Utilization Rate")+
  # theme(plot.title = element_text( face = "bold"))
BK4

```



# 主图-合并出图 
```{r}


# 最终设置版本
design1 <- c("123
              456
              789")
(P_Pre + P_Rec + P_F1 +P_BC +  P_L1 +  P_L2+   P_rJSD + P_SeqNum+ P_SeqFreq ) +
  plot_layout(design = design1)
ggsave(filename = "03.figureUP/M4_BK3.pdf",height = 6.5,width = 6.5)



# 最终设置版本
design1 <- c("123
              456
              789")
(P_Pre + P_Rec + P_F1 +P_BC +  P_L1 +  P_L2+   P_rJSD + P_SeqFreq + plot_spacer()  ) +
  plot_layout(design = design1)
ggsave(filename = "03.figureUP/M4_BK3_1.pdf",height = 6.5,width = 6.5)



P_CorARGs2 /P_CorARGs*theme(legend.position = "none")
ggsave(filename = "03.figureUP/M4_BK4.pdf",height = 6.5,width = 3.5)


# 补充附图
# 修改后的代码
(P_CorARGsBP1$Plot | P_CorARGsBP2$Plot | P_CorARGsReads1$Plot) /
(P_CorARGsReads2$Plot | P_CorARGsContigs1$Plot | P_CorARGsContigs2$Plot) + 
  plot_layout(guides = 'collect') +
  plot_annotation(tag_levels = 'a') &  # 可选：为每个子图添加A、B、C等标签
  theme(plot.title = element_text(face = "bold"),plot.tag = element_text(face = "bold"))

ggsave(filename = "03.figureUP/M4_BK2.pdf", height = 6, width = 10)


```


# 输出-数据存储
```{r}
# 数据存储
# 基因组信息表
attach(refseq_sim_1200)
# 物种真实丰度
attach(BacTvalue)
# ARGs真实丰度
attach(ARGsTvalue)
# 所有BK最终版本
attach(AllBK_filter)
# 所有checkM评估的数据
attach(MAG_checkm)
# 序列利用率，需要修改为ARGs
attach(Reads_use_filter_na)
save(refseq_sim_1200,
     BacTvalue,
     ARGsTvalue,
     AllBK_filter,
     MAG_tax_final,
     Reads_use_filter_na,file = "02.datasave/04.BPBK.Rdata")

```



